name: vagrant-up

on:
  push:
  pull_request:

jobs:
  vagrant-up:
    name: Run test-ansible-box
    runs-on: macos-10.15
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show vagrant version
        run: vagrant --version

      - name: Install vagrant plugins
        run: |
          set -vxeuo pipefail
          vagrant plugin install vagrant-vbguest
          vagrant plugin install vagrant-disksize

      - name: vagrant up
        run: |
          set -vxeuo pipefail
          vagrant up

      - name: vagrant ssh
        run: |
          set -vxeuo pipefail
          vagrant ssh -c "echo 'Hello, World!'"
